### PR TITLE
Added L4D2 to games.kv

### PR DESCRIPTION
**Pull request by andrewchenk**

### CODE REVIEW

**Comment by andrewchenk** [comment]
Thanks for approving. I also want to add this autoexec for those recording L4D2 at high framerates: 

https://pastebin.com/eQU8niXP

**Comment by AronParker** [comment]
Hey, I merged your request, however I don't think adding built-in configs would make a lot of sense right now. Besides most of the settings seem to be networking related and don't affect the graphics so much, which is kind of an important deal considering it's a recorder. Thanks for your contribution though and let me know if you have any more suggestions.

**Comment by andrewchenk** [comment]
Hey, thanks for the reply! I didn't mean to have it included in the repo, and I agree it isn't suitable. Just wanted to post the cfg somewhere so that people trying to record L4D2 would find it, and figured why not here.

Thanks again for making the software, this has been my only solution for frame blending since SourceDemoRender doesn't work with the game and SrcDemo2 is way too slow.

**Comment by AronParker** [comment]
I grant permission to delete pull request #23 from AronParker/AviRecorder.

**Pull request merged**
